### ISSUE TITLE
引入next.js项目，报错如下

### ISSUE THREAD

**Issue by baowanli719** [ant-design/x#291]
### 重现步骤

引入next.js项目，报错如下，需要注意什么吗
-  代码部分
```
import { Sender } from '@ant-design/x';
import { App, Flex } from 'antd';
import React, { useState } from 'react';

const MessageFormMobile = () => {
    const [value, setValue] = useState<string>('Hello? this is X!');
    const [loading, setLoading] = useState<boolean>(false);

    const { message } = App.useApp();

    return (
        <Sender value="Force as loading" loading readOnly /> 
    )
}

export default MessageFormMobile
```

- 报错内容
```
 ⚠ Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
 ✓ Compiled /api/hisMessage in 257ms (204 modules)
 ✓ Compiled in 3.3s (6535 modules)
 ⨯ /opt/ai-app/node_modules/antd/es/theme/useToken.js:9
import React from 'react';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1153:20)
    at Module._compile (node:internal/modules/cjs/loader:1205:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at mod.require (/opt/ai-app/node_modules/next/dist/server/require-hook.js:64:28)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/opt/ai-app/node_modules/@ant-design/x/lib/theme/useToken.js:15:17)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19) {
  page: '/'
}

```

### 版本

1.0.1

### 您在哪些浏览器上遇到了这个问题？

Microsoft Edge

**Comment by zombieJ** [comment]
添加 `use client`

**Comment by baowanli719** [comment]
> 添加 `use client`

当前页面增加这个'use client';后，还是报一样的错误呢

**Comment by YumoImer** [comment]
https://github.com/vercel/next.js/issues/47177

这似乎是 node 的 bug

**Comment by YumoImer** [comment]
### 环境信息

- `node`: 20.5.0
- `react`: 18.3.1
- `next`: 15.0.3
- `@ant-deign/x`: 1.0.1

### 相关截图

按你提供的 Page 代码，以及上述环境，可以正常启动项目。

![image](https://github.com/user-attachments/assets/cdbf101e-d8dc-4b60-abe4-a568283c1d4d)

### React 19 告警

这个后续我们会处理。

React 官方说明：https://zh-hans.react.dev/blog/2024/04/25/react-19-upgrade-guide?utm_source=chatgpt.com#deprecated-element-ref

![image](https://github.com/user-attachments/assets/3081c704-14e2-4582-a66b-588b43b1d4b8)


@JJack27 @baowanli719
