### ISSUE TITLE
Cannot read properties of undefined (reading '_context')

### ISSUE THREAD

**Issue by cjianyu361** [ant-design/x#365]
### 重现步骤

项目：
"@umijs/max": "^4.1.1",
"antd": "^5.4.0",
"@ant-design/x": "^1.0.2",
"@types/react": "^18.0.33",
"@types/react-dom": "^18.0.11",

操作过程：
安装： npm i @ant-design/x
引入组件：import {Bubble} from "@ant-design/x";
简单使用：<Bubble content="Hello world!" />
然后就出现异常了。
Uncaught TypeError: Cannot read properties of undefined (reading '_context')
    at Object.useContext (react.development.js:1604:1)
    at useInternalToken (useToken.js:69:1)
    at useToken (genStyleUtils.js:20:1)
    at genStyleUtils.js:118:1
    at genStyleUtils.js:49:1
    at Conversations (index.js:59:1)
    at renderWithHooks (react-dom.development.js:16175:1)
    at mountIndeterminateComponent (react-dom.development.js:20913:1)
    at beginWork (react-dom.development.js:22416:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4161:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4210:1)
    at invokeGuardedCallback (react-dom.development.js:4274:1)
    at beginWork$1 (react-dom.development.js:27405:1)
    at performUnitOfWork (react-dom.development.js:26513:1)
    at workLoopConcurrent (react-dom.development.js:26499:1)
    at renderRootConcurrent (react-dom.development.js:26461:1)
    at performConcurrentWorkOnRoot (react-dom.development.js:25694:1)
    at workLoop (scheduler.development.js:266:1)
    at flushWork (scheduler.development.js:239:1)
    at performWorkUntilDeadline (scheduler.development.js:533:1)
    at queue.<computed> (task.js:62:1)
    at run (task.js:36:1)
    at MessagePort.eventListener (task.js:47:1)

### 当前行为

异常：
![Uploading image.png…]()

### 预期行为

正常使用

### 上下文

import {Bubble} from "@ant-design/x";
<Bubble content="Hello world!" />

### 版本

1.0.2

**Comment by YumoImer** [comment]
重复了，查看下 #253
